name: Release
on:
  push:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          commit-message: 'ci(versioning): Bumps version to {{version}}'
        env:
          GITHUB_USER: jhqci
          GITHUB_EMAIL: jacobhq.extensions@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        uses: pnpm/action-setup@v2.0.1
        with:
          # Version of PNPM to install
          version: 6.11.0
      - uses: creepinson/pnpm-action@master
        with:
          arguments: '["install", "build"]'
      - uses: actions/upload-artifact@v2
        name: Zip file
        with:
          name: build
          path: ${{ github.workspace }}/extension
