name: Release
on:
  push:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          commit-message: 'ci(versioning): Bumps version to {{version}}'
        env:
          GITHUB_USER: jhqci
          GITHUB_EMAIL: jacobhq.extensions@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        name: Zip file
        with:
          name: build
          path: ${{ github.workspace }}/src
